/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class VenderCoche extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VenderCoche.class.getName());
    private User u;
    private VentanaPrincipal vp;
    private Connection conn;

    /**
     * Creates new form VenderCoche
     *
     * @param u
     * @param vp
     * @param conn
     */
    public VenderCoche(User u, VentanaPrincipal vp, Connection conn) {
        initComponents();
        this.u = u;
        this.vp = vp;
        this.conn = conn;
        try {
            PreparedStatement ps = conn.prepareStatement("SELECT email FROM login WHERE usuario = ?");
            ps.setString(1, u.getNombre());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                email.setText(rs.getString("email"));
            }
            rs.close();
            ps.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error con la base de datos:\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private VenderCoche() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void limpiar() {
        modelo.setText(null);
        color.setText(null);
        matricula.setText(null);
        precio.setText(null);
        kilometros.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        kilometros = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        matricula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vender Coche");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("VENDER COCHE");

        jLabel2.setText("Modelo :");

        jLabel3.setText("Color :");

        jLabel4.setText("Precio :");

        jLabel5.setText("Kilómetros :");

        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });

        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });

        kilometros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilometrosActionPerformed(evt);
            }
        });

        jLabel6.setText("Email contacto :");

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setEnabled(false);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        enter.setText("Poner Anuncio");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        volver.setText("Página Principal");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jLabel7.setText("Matrícula :");

        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(kilometros, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(precio)
                                .addComponent(color)
                                .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(modelo))
                            .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(enter)
                        .addGap(38, 38, 38)
                        .addComponent(volver)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter)
                    .addComponent(volver))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
    }//GEN-LAST:event_emailActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        String err = "";
        if (modelo.getText().isBlank()) {
            err += "El modelo no puede estar vacío\n";
        }
        if (color.getText().isBlank()) {
            err += "El color no puede estar vacío\n";
        }
        if (matricula.getText().isBlank()) {
            err += "La matrícula no puede estar vacía\n";
        }
        if (precio.getText().isBlank()) {
            err += "El precio no puede estar vacío\n";
        }
        if (kilometros.getText().isBlank()) {
            err += "Los kilómetros no pueden estar vacíos\n";
        }
        //Validación matrícula
        String m = matricula.getText();
        boolean error = false;
        if (m.length() != 8) {
            error = true;
        } else {
            for (int i = 0; i < m.length(); i++) {
                char c = m.charAt(i);

                if (i <= 3) {
                    if (!Character.isDigit(c)) {
                        error = true;
                    }
                } else if (i == 4) {
                    if (c != ' ') {
                        error = true;
                    }
                } else {
                    if (!Character.isLetter(c)) {
                        error = true;
                    }
                }
            }
        }
        if (error) {
            err += "Error en la matricula\n";
        }
        int km = 0;
        try {
            km = Integer.parseInt(kilometros.getText());
        } catch (NumberFormatException e) {
            err += "Error con los kilómetros (no se admiten)\n";
        }
        double prz = 0;
        try {
            String texto = precio.getText();
            if (!texto.matches("^\\d+(\\.\\d{1,2})?$")) {
                throw new NumberFormatException();
            }
            prz = Double.parseDouble(texto);
        } catch (NumberFormatException e) {
            err += "Error con el precio (usa '.' y máximo 2 decimales)\n";
        }
        if (err.isBlank()) {
            try {
                PreparedStatement ps2 = conn.prepareStatement("SELECT modelo FROM coches WHERE matricula = ?");
                ps2.setString(1, m);
                ResultSet rs = ps2.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Esa matrícula ya se encuentra en uso", "Matrícula en uso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    PreparedStatement ps = conn.prepareStatement("INSERT INTO coches(matricula,modelo,color,email,kilometros,precio) "
                            + "VALUES(?,?,?,?,?,?)");
                    ps.setString(1, m);
                    ps.setString(2, modelo.getText());
                    ps.setString(3, color.getText());
                    ps.setString(4, email.getText());
                    ps.setInt(5, km);
                    ps.setDouble(6, prz);
                    ps.executeUpdate();
                    ps.close();
                    limpiar();
                }
                ps2.close();
                rs.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error con la base de datos", "ERROR SQL", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, err, "Errores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enterActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        vp.setLocationRelativeTo(null);
        this.setVisible(false);
        vp.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        color.requestFocus();
    }//GEN-LAST:event_modeloActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        precio.requestFocus();
    }//GEN-LAST:event_colorActionPerformed

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        kilometros.requestFocus();
    }//GEN-LAST:event_precioActionPerformed

    private void kilometrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilometrosActionPerformed
        matricula.requestFocus();
    }//GEN-LAST:event_kilometrosActionPerformed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        enter.doClick();
    }//GEN-LAST:event_matriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VenderCoche().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField color;
    private javax.swing.JTextField email;
    private javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField kilometros;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField precio;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
