/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.awt.Image;
import java.sql.*;
import javax.swing.ImageIcon;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class VentanaRegistro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRegistro.class.getName());
    private VentanaLogin vL;
    private Connection conn;

    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro(VentanaLogin vL, Connection c) {
        initComponents();
        this.vL = vL;
        conn = c;
        ImageIcon imagen = new ImageIcon("imagenRegistro.jpg");
        Image img = imagen.getImage();
        Image imgEscalada = img.getScaledInstance(
                icono.getWidth(),
                icono.getHeight(),
                Image.SCALE_SMOOTH
        );
        icono.setIcon(new ImageIcon(imgEscalada));
    }

    private VentanaRegistro() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etRegistro = new javax.swing.JLabel();
        etUsuario = new javax.swing.JLabel();
        etContraseña = new javax.swing.JLabel();
        etConfContraseña = new javax.swing.JLabel();
        etEmail = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        contraseña2 = new javax.swing.JTextField();
        icono = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        etRegistro.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        etRegistro.setForeground(new java.awt.Color(51, 51, 51));
        etRegistro.setText("REGISTRO");

        etUsuario.setText("Usuario :");

        etContraseña.setText("Contraseña :");

        etConfContraseña.setText("Confirmar Contraseña :");

        etEmail.setText("Email :");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        contraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseña2ActionPerformed(evt);
            }
        });

        register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        register.setText("REGISTRARME");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        volver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(etRegistro)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etEmail)
                                .addGap(18, 18, 18)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etUsuario)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etContraseña)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etConfContraseña)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contraseña2)))
                            .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(register)
                        .addGap(18, 18, 18)
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(etRegistro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etUsuario)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etEmail)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etConfContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register)
                    .addComponent(volver))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String errores = "";
        // Validación del nombre de usuario
        String n = nombre.getText();
        if (!n.isEmpty()) {
            try {
                PreparedStatement ps = conn.prepareStatement("SELECT 1 FROM login WHERE usuario = ?");
                ps.setString(1, n);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    errores += "Nombre de usuario ya en uso \n";
                }
                ps.close();
                rs.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error con la base de datos: \n" + e.getMessage(), "Error Base de Datos", JOptionPane.ERROR_MESSAGE);
            }
            if (n.length() < 5) {
                errores += "Nombre de usuario muy corto \n";
            }
            if (n.length() > 20) {
                errores += "Nombre de usuario muy largo \n";
            }
        } else {
            errores += "El usuario no puede estar vacío \n";
        }
        for (int i = 0; i < n.length(); i++) {
            char c = n.charAt(i);
            if (!Character.isDigit(c) && !Character.isLetter(c)) {
                errores += "El nombre de usuario no puede contener caracteres especiales \n";
            }
        }
        // Validación del email
        String e = email.getText();
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(e);
        if (!matcher.matches()) {
            errores += "Email inválido, revisa el email introducido \n";
        }
        // Validación de las contraseñas
        String p = contraseña.getText();
        if (!p.isBlank()) {
            if (p.length() < 8) {
                errores += "Contraseña muy corta \n";
            }
            if (p.length() > 30) {
                errores += "Contraseña muy larga \n";
            }
        } else {
            errores += "La contraseña no puede estar vacía \n";
        }
        boolean valida = false;
        for (int i = 0; i < p.length(); i++) {
            char c = p.charAt(i);
            if (!Character.isDigit(c) && !Character.isLetter(c)) {
                valida = true;
            }
            if (c == ' ') {
                errores += "La contraseña no puede contener espacios en blanco \n";
            }
        }
        if (!valida) {
            errores += "La contraseña debe contener al menos 1 carácter especial \n";
        }
        if (!p.equals(contraseña2.getText())) {
            errores += "Las contraseñas no coinciden \n";
        }
        //Envío final
        if (errores.isBlank()) {
            try {
                PreparedStatement ps = conn.prepareStatement("INSERT INTO login(usuario,contrasena,email) "
                        + "VALUES(?,?,?)");
                ps.setString(1, n);
                ps.setString(2, p);
                ps.setString(3, e);
                ps.executeUpdate();
                ps.close();
                JOptionPane.showMessageDialog(null, "Usuario Registrado correctamente");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error con la base de datos: \n" + ex.getMessage(), "Error Base de Datos", JOptionPane.ERROR_MESSAGE);
            }
            volver.doClick();
        } else {
            JOptionPane.showMessageDialog(null, errores, "Lista de errores", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registerActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.setVisible(false);
        limpiar();
        vL.setLocationRelativeTo(null);
        vL.limpiar();
        vL.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        email.requestFocus();
    }//GEN-LAST:event_nombreActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        contraseña.requestFocus();
    }//GEN-LAST:event_emailActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        contraseña2.requestFocus();
    }//GEN-LAST:event_contraseñaActionPerformed

    private void contraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseña2ActionPerformed
        register.doClick();
    }//GEN-LAST:event_contraseña2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaRegistro().setVisible(true));
    }

    public void limpiar() {
        nombre.setText(null);
        email.setText(null);
        contraseña.setText(null);
        contraseña2.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField contraseña2;
    private javax.swing.JTextField email;
    private javax.swing.JLabel etConfContraseña;
    private javax.swing.JLabel etContraseña;
    private javax.swing.JLabel etEmail;
    private javax.swing.JLabel etRegistro;
    private javax.swing.JLabel etUsuario;
    private javax.swing.JLabel icono;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton register;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
