/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.awt.*;
import java.sql.*;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author Alumno
 */
public class VentanaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaLogin.class.getName());
    private VentanaRegistro vR;
    private Connection conn;
    private Statement stat;

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        password.setEchoChar('*');
        try {
            conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/concesionario", "root", "");
            stat = conn.createStatement();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error con la base de datos: \n" + e.getMessage(), "Error Base de Datos", JOptionPane.ERROR_MESSAGE);
        }
        vR = new VentanaRegistro(this, conn);
        //Imagen superior
        ImageIcon imagen = new ImageIcon("imagen.jpg");
        Image img = imagen.getImage();
        Image imgEscalada = img.getScaledInstance(
                icono.getWidth(),
                icono.getHeight(),
                Image.SCALE_SMOOTH
        );
        icono.setIcon(new ImageIcon(imgEscalada));
        //Imagen inferior
        ImageIcon imagen2 = new ImageIcon("imagen2.jpg");
        Image img2 = imagen2.getImage();
        Image imgEscalada2 = img2.getScaledInstance(
                icono2.getWidth(),
                icono2.getHeight(),
                Image.SCALE_SMOOTH
        );
        icono2.setIcon(new ImageIcon(imgEscalada2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etLogin = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        icono2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        passwdLabel = new javax.swing.JLabel();
        vendedor = new javax.swing.JCheckBox();
        comprador = new javax.swing.JCheckBox();
        login = new javax.swing.JButton();
        register = new javax.swing.JButton();
        rLabel = new javax.swing.JLabel();
        lLabel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        mostrar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        etLogin.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        etLogin.setForeground(new java.awt.Color(0, 0, 204));
        etLogin.setText("LOGIN");

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userLabel.setText("Usuario :");

        passwdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwdLabel.setText("Contraseña :");

        vendedor.setText("Sesión única");
        vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedorActionPerformed(evt);
            }
        });

        comprador.setSelected(true);
        comprador.setText("Mantener sesión abierta");
        comprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compradorActionPerformed(evt);
            }
        });

        login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        register.setText("REGISTRARSE");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        rLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rLabel.setText("Aún no te has registrado?");

        lLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lLabel.setText("Acceso a tu seccion usuario");

        mostrar.setText("Mostrar Contraseña");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rLabel)
                            .addComponent(lLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwdLabel)
                                    .addComponent(userLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(password)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comprador)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vendedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mostrar)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(icono2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(icono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(etLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(etLogin)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwdLabel)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE)
                        .addComponent(comprador)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vendedor)
                            .addComponent(mostrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(login)
                            .addComponent(lLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(register)
                            .addComponent(rLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(icono2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        password.requestFocus();
    }//GEN-LAST:event_userActionPerformed

    private void compradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compradorActionPerformed
        if (comprador.isSelected()) {
            vendedor.setSelected(false);
        } else {
            vendedor.setSelected(true);
        }
    }//GEN-LAST:event_compradorActionPerformed

    private void vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedorActionPerformed
        if (vendedor.isSelected()) {
            comprador.setSelected(false);
        } else {
            comprador.setSelected(true);
        }
    }//GEN-LAST:event_vendedorActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        vR.setLocationRelativeTo(null);
        vR.limpiar();
        this.setVisible(false);
        vR.setVisible(true);
    }//GEN-LAST:event_registerActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try {
            PreparedStatement ps = conn.prepareStatement("SELECT contrasena FROM login WHERE usuario = ?");
            ps.setString(1, user.getText());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String passwd = rs.getString("contrasena");
                if (!passwd.equals(password.getText())) {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "Error contraseña", JOptionPane.ERROR_MESSAGE);
                } else {
                    VentanaPrincipal vp = new VentanaPrincipal(new User(user.getText(), password.getText()), conn);
                    vp.setLocationRelativeTo(null);
                    this.dispose();
                    vR.dispose();
                    vp.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no encontrado, revisa el usuario introducido", "Error Usuario", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error con la base de datos: \n" + e.getMessage(), "Error Base de Datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        if (mostrar.isSelected()) {
            password.setEchoChar('*');
        } else {
            password.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_mostrarActionPerformed
    
    public void limpiar() {
        user.setText(null);
        password.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox comprador;
    private javax.swing.JLabel etLogin;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel icono2;
    private javax.swing.JLabel lLabel;
    private javax.swing.JButton login;
    private javax.swing.JCheckBox mostrar;
    private javax.swing.JLabel passwdLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel rLabel;
    private javax.swing.JButton register;
    private javax.swing.JTextField user;
    private javax.swing.JLabel userLabel;
    private javax.swing.JCheckBox vendedor;
    // End of variables declaration//GEN-END:variables
}
